import { appendFileSync } from "node:fs";
import builtins from "builtin-modules";
import esbuild from "esbuild";

const banner = `/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin. */`;

const isProductionMode = process.argv[2] === "production";
const isAnalyzeMode = process.argv[2] === "analyze";
const isWatchMode = process.argv[2] === "watch";

//──────────────────────────────────────────────────────────────────────────────

const config = {
	entryPoints: ["src/main.ts"],
	banner: { js: banner + "\n" },
	outfile: "dist/main.js",
	bundle: true,
	// biome-ignore format: no need to inspect this regularly
	external: ["obsidian", "electron", "@codemirror/autocomplete", "@codemirror/collab", "@codemirror/commands", "@codemirror/language", "@codemirror/lint", "@codemirror/search", "@codemirror/state", "@codemirror/view", "@lezer/common", "@lezer/highlight", "@lezer/lr", ...builtins],
	format: "cjs",
	target: "es2022",
	sourcemap: isProductionMode || isAnalyzeMode ? false : "inline",
	minify: isProductionMode || isAnalyzeMode,
	drop: ["debugger"],
	treeShaking: true,
	logLevel: isAnalyzeMode ? "silent" : "info",
	metafile: isAnalyzeMode,
}

//──────────────────────────────────────────────────────────────────────────────

// DOCS https://esbuild.github.io/api/index#metafile
if (config.metafile) {
	const sizes = await esbuild.analyzeMetafile(config.metafile, { verbose: false });
	console.info(sizes);
}

// FIX prevent Obsidian from removing the source map when using dev build
// https://forum.obsidian.md/t/source-map-trimming-in-dev-builds/87612
if (!isProductionMode) {
	appendFileSync(import.meta.dirname + "/dist/main.js", "\n/* nosourcemap */");
}

const ctx = await esbuild.context(config);

if (isWatchMode) {
	await ctx.watch();
	console.log('Watching...');
} else {
	await ctx.rebuild();
	await ctx.dispose();
	console.log('Build complete');
}
